### PR TITLE
Use an explicit library for assertions #29

### PR DESCRIPTION
**Pull request by ohaddahan**
https://github.com/metaplex-foundation/beet/issues/29

### CODE REVIEW

**Comment by ohaddahan** [comment]
Bump @thlorenz @lorisleiva

**Comment by ohaddahan** [comment]
@blockiosaurus anyone can take a look? Thanks.

**Review by blockiosaurus — APPROVED** [review]

**Comment by ohaddahan** [comment]
FYI version wasn't pushed to `npm` @blockiosaurus .

**Comment by blockiosaurus** [comment]
Cursed these unautomated old repos. Published both.

**Comment by ohaddahan** [comment]
> Cursed these unautomated old repos. Published both.

Thank you, appreciate it.

**Pull request merged**
